import 'package:flutter/cupertino.dart';
import 'package:single_child_widgets_examples/ui_screens/AlignScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/AspectRatioScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/BaselineScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/CardScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/ConstrainedBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/CustomSingleChildLayoutScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/ExpandedScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/FittedBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/FractionallySizedBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/IntrinsicHeightScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/IntrinsicWidthScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/LimitedBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/OffstageScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/OverflowBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/PaddingScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/SizedBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/SizedOverflowBoxScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/TransformScreen.dart';
import 'package:single_child_widgets_examples/ui_screens/VideoPlayerScreen.dart';

var widgetList = <Widget>[
  const AlignScreen(),
  const AspectRatioScreen(),
  const BaselineScreen(),
  const CardScreen(),
  const ConstrainedBoxScreen(),
  const CustomSingleChildLayoutScreen(),
  const ExpandedScreen(),
  const FittedBoxScreen(),
  const FractionallySizedBoxScreen(),
  const IntrinsicHeightScreen(),
  const IntrinsicWidthScreen(),
  const LimitedBoxScreen(),
  const OffstageScreen(),
  const OverflowBoxScreen(),
  const PaddingScreen(),
  const SizedBoxScreen(),
  const SizedOverflowBoxScreen(),
  const TransformScreen(),
  const VideoPlayerScreen(),
];
